services:
  video-admin:
    image: ${IMAGE}
    container_name: ${APP_NAME}
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    ports:
      - 82:82
    networks:
      - video

networks:
  video:
    external: true
